run:
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c1355_tb.v circuits/c1355.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c17_tb.v circuits/c17.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c2670_tb.v circuits/c2670.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c3540_tb.v circuits/c3540.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c432_tb.v circuits/c432.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c499_tb.v circuits/c499.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c5315_tb.v circuits/c5315.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c6288_tb.v circuits/c6288.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c7552_tb.v circuits/c7552.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/c880_tb.v circuits/c880.v
	rm -rf INCA_libs
	ncverilog +sv +access+rw +nctimescale+1ns/1ns testbenches/mux_tb.v circuits/mux.v
	rm -rf INCA_libs
